# .github/workflows/ci-cd.yml

name: main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: Java 11 설정
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드 (테스트 제외)
        run: ./gradlew build -x test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: JAR 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.0
        with:
          host:     ${{ secrets.SERVER_IP }}      # ← 네 Secret 이름
          username: ec2-user
          key:      ${{ secrets.SSH_KEY }}        # ← 네 Secret 이름
          source:   build/libs/library-app-0.0.1-SNAPSHOT.jar  # ← 여만 build/libs로
          target:   /home/ec2-user/app/

      - name: 원격 서버 애플리케이션 재시작 (SSH)
        uses: appleboy/ssh-action@v0.1.0
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ec2-user
          key:      ${{ secrets.SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/app/library-app-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev &
