# .github/workflows/ci-cd.yml

name: ci-cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Grant gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Transfer JAR via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ec2-user
          key:      ${{ secrets.SSH_KEY }}
          source:   build/libs/library-app-0.0.1-SNAPSHOT.jar
          target:   /home/ec2-user/library-app/build/libs/

      - name: Restart app via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ec2-user
          key:      ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/library-app
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/library-app-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev &
