# .github/workflows/ci-cd.yml

name: ci-cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드 (테스트 제외)
        run: ./gradlew build -x test

      - name: 워크스페이스 구조 디버깅
        run: |
          echo "=== 현재 디렉토리 ==="
          pwd
          echo "=== 전체 파일 목록 ==="
          ls -R .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: JAR 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.0
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ec2-user
          key:      ${{ secrets.SSH_KEY }}
          source:   '**/build/libs/*.jar'
          target:   /home/ec2-user/library-app/

      - name: 서버 재시작 via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ec2-user
          key:      ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/library-app
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/*.jar --spring.profiles.active=dev &
